import {
  useEffect,
  useMemo,
  useState,
} from 'react'

import {
  AlertCircle,
  CheckCircle2,
  Circle,
  RotateCcw,
  ShieldCheck,
} from 'lucide-react'

import { apiRequest } from '../services/api'

const EMPTY_REVIEW = {
  sourceDatasetVerified: false,
  targetDatasetVerified: false,
  rejectedRowsVerified: false,
  transactionIdentifiersCompared: false,
  rootCauseSupported: false,
  actionSupported: false,
  resolutionAppropriate: false,
}

const RECONCILIATION_RETURN_REASONS = [
  {
    value: '',
    label: 'Select return reason',
  },
  {
    value: 'EVIDENCE_OVERLOOKED',
    label: 'Evidence Overlooked',
  },
  {
    value: 'INSUFFICIENT_EVIDENCE',
    label: 'Insufficient Evidence',
  },
  {
    value: 'ROOT_CAUSE_UNCLEAR',
    label: 'Root Cause Unclear',
  },
  {
    value: 'DATASET_REVIEW_INCOMPLETE',
    label: 'Dataset Review Incomplete',
  },
  {
    value: 'TRANSACTION_COMPARISON_INCORRECT',
    label: 'Transaction Comparison Incorrect',
  },
  {
    value: 'ACTION_NOT_SUPPORTED',
    label: 'Proposed Action Not Supported',
  },
  {
    value: 'RESOLUTION_INCOMPLETE',
    label: 'Resolution Incomplete',
  },
  {
    value: 'OTHER',
    label: 'Other',
  },
]

const DATA_QUALITY_RETURN_REASONS = [
  {
    value: '',
    label: 'Select return reason',
  },
  {
    value: 'EVIDENCE_OVERLOOKED',
    label: 'Affected Evidence Overlooked',
  },
  {
    value: 'INSUFFICIENT_EVIDENCE',
    label: 'Insufficient Data-Integrity Evidence',
  },
  {
    value: 'ROOT_CAUSE_UNCLEAR',
    label: 'Root Cause Unclear',
  },
  {
    value: 'DATASET_REVIEW_INCOMPLETE',
    label: 'Original Dataset Review Incomplete',
  },
  {
    value: 'TRANSACTION_COMPARISON_INCORRECT',
    label: 'Affected Record Verification Incorrect',
  },
  {
    value: 'ACTION_NOT_SUPPORTED',
    label: 'Remediation Not Supported by Evidence',
  },
  {
    value: 'RESOLUTION_INCOMPLETE',
    label: 'Remediation Instruction Incomplete',
  },
  {
    value: 'OTHER',
    label: 'Other',
  },
]

function formatLabel(value) {
  if (!value) return '—'

  return String(value)
    .replaceAll('_', ' ')
    .toLowerCase()
    .replace(/\b\w/g, (letter) =>
      letter.toUpperCase(),
    )
}

function CheckerReviewPanel({
  caseRecord,
  currentUser,
  onCaseUpdated,
}) {
  const [reviewChecks, setReviewChecks] =
    useState(EMPTY_REVIEW)

  const [
    checkerComment,
    setCheckerComment,
  ] = useState('')

  const [
    returnReason,
    setReturnReason,
  ] = useState('')

  const [
    commentAutoGenerated,
    setCommentAutoGenerated,
  ] = useState(false)

  const [
    processingAction,
    setProcessingAction,
  ] = useState(null)

  const [error, setError] =
    useState('')

  const [success, setSuccess] =
    useState('')

  const canReview =
    currentUser?.role === 'CHECKER' &&
    caseRecord?.status ===
      'PENDING_CHECKER_APPROVAL'

  /*
   * ----------------------------------------
   * CASE ORIGIN
   * ----------------------------------------
   *
   * One shared BankSync Case engine:
   *
   * RECONCILIATION_EXCEPTION
   * → source/target reconciliation evidence
   *
   * DATA_QUALITY_ISSUE
   * → pre-reconciliation data-integrity evidence
   */
  const isDataQualityCase =
    caseRecord?.originType ===
      'DATA_QUALITY_ISSUE' ||
    Boolean(
      caseRecord?.dataQualityIssueId &&
        !caseRecord?.exceptionId,
    )

  /*
   * ----------------------------------------
   * RECONCILIATION CONTEXT
   * ----------------------------------------
   */
  const reconciliation =
    caseRecord?.exceptionId
      ?.reconciliationId

  const sourceInvalidRows =
    Number(
      reconciliation
        ?.sourceUploadId
        ?.invalidRows || 0,
    )

  const targetInvalidRows =
    Number(
      reconciliation
        ?.targetUploadId
        ?.invalidRows || 0,
    )

  /*
   * ----------------------------------------
   * DATA QUALITY CONTEXT
   * ----------------------------------------
   */
  const dataQualityIssue =
    caseRecord?.dataQualityIssueId

  const originalUpload =
    caseRecord?.originalUploadId ||
    dataQualityIssue?.uploadId

  const originalInvalidRows =
    Number(
      originalUpload?.invalidRows || 0,
    )

  const rejectedRowsRequired =
    isDataQualityCase
      ? originalInvalidRows > 0
      : sourceInvalidRows > 0 ||
        targetInvalidRows > 0

  /*
   * ----------------------------------------
   * STORED CHECKER REVIEW
   * ----------------------------------------
   */
  useEffect(() => {
    const storedReview =
      caseRecord?.checkerReview

    setReviewChecks({
      ...EMPTY_REVIEW,
      ...(storedReview || {}),
    })

    setCheckerComment(
      caseRecord?.checkerComment || '',
    )

    setReturnReason(
      caseRecord?.checkerReturnReason ||
        '',
    )

    setCommentAutoGenerated(false)

    setError('')
    setSuccess('')
  }, [caseRecord?._id])

  /*
   * ----------------------------------------
   * ORIGIN-AWARE VERIFICATION CHECKLIST
   * ----------------------------------------
   *
   * The underlying schema is still shared.
   *
   * For Data Quality:
   * - sourceDatasetVerified means the
   *   original uploaded dataset was verified.
   * - transactionIdentifiersCompared means
   *   the affected records/detected defect
   *   were independently verified.
   *
   * targetDatasetVerified is NOT required
   * because there is no target reconciliation
   * dataset at this stage.
   */
  const verificationItems =
    useMemo(() => {
      if (isDataQualityCase) {
        const items = [
          {
            key:
              'sourceDatasetVerified',
            label:
              'Original uploaded dataset independently verified',
            description:
              'Open the original uploaded banking dataset yourself and confirm the Maker reviewed the correct source evidence.',
          },
        ]

        if (rejectedRowsRequired) {
          items.push({
            key:
              'rejectedRowsVerified',
            label:
              'Rejected rows independently verified',
            description:
              'Review rejected rows from the original upload and confirm relevant evidence was not excluded during validation.',
          })
        }

        items.push(
          {
            key:
              'transactionIdentifiersCompared',
            label:
              dataQualityIssue
                ?.issueType ===
                'DUPLICATE_TRANSACTION_ID'
                ? 'Duplicate transaction-ID evidence independently confirmed'
                : dataQualityIssue
                      ?.issueType ===
                    'DUPLICATE_REFERENCE'
                  ? 'Duplicate reference evidence independently confirmed'
                  : dataQualityIssue
                        ?.issueType ===
                        'REVERSAL_WITHOUT_ORIGINAL' ||
                      dataQualityIssue
                        ?.issueType ===
                        'REVERSAL_AMOUNT_MISMATCH'
                    ? 'Original / reversal evidence independently confirmed'
                    : 'Affected records independently verified',
            description:
              'Inspect the affected transaction records yourself and confirm the detected data-integrity defect from the underlying dataset.',
          },

          {
            key:
              'rootCauseSupported',
            label:
              'Maker root cause is supported by the verified evidence',
            description:
              'Confirm that the Maker’s stated cause is justified by the evidence. A scanner finding alone does not prove the business root cause.',
          },

          {
            key:
              'actionSupported',
            label:
              'Maker remediation recommendation is supported by evidence',
            description:
              'Confirm that the recommended source-data action follows logically from the verified data-integrity issue.',
          },

          {
            key:
              'resolutionAppropriate',
            label:
              'Recommended remediation is operationally appropriate',
            description:
              'Confirm that the recommendation preserves the original BankSync upload, routes any correction through the proper source/import process, and requires verification before reconciliation use.',
          },
        )

        return items
      }

      const items = [
        {
          key:
            'sourceDatasetVerified',
          label:
            'Source dataset independently verified',
          description:
            'Inspect the source dataset yourself and confirm whether the Maker’s statement about the source record is correct.',
        },

        {
          key:
            'targetDatasetVerified',
          label:
            'Target dataset independently verified',
          description:
            'Inspect the target dataset yourself and verify the relevant transaction record.',
        },
      ]

      if (rejectedRowsRequired) {
        items.push({
          key:
            'rejectedRowsVerified',
          label:
            'Rejected rows independently verified',
          description:
            'Review rejected rows and confirm that relevant transaction evidence was not overlooked.',
        })
      }

      items.push(
        {
          key:
            'transactionIdentifiersCompared',
          label:
            'Transaction identifiers independently compared',
          description:
            'Compare transaction ID, reference, account, amount, date, status, and other relevant reconciliation fields.',
        },

        {
          key:
            'rootCauseSupported',
          label:
            'Maker root cause supported by evidence',
          description:
            'Confirm that the Maker’s root cause follows from the reconciliation records you independently verified.',
        },

        {
          key:
            'actionSupported',
          label:
            'Proposed action supported by evidence',
          description:
            'Confirm that the proposed action logically follows from the verified reconciliation discrepancy.',
        },

        {
          key:
            'resolutionAppropriate',
          label:
            'Resolution is operationally appropriate',
          description:
            'Confirm that the proposed resolution properly addresses the verified reconciliation problem.',
        },
      )

      return items
    }, [
      dataQualityIssue,
      isDataQualityCase,
      rejectedRowsRequired,
    ])

  const returnReasons =
    isDataQualityCase
      ? DATA_QUALITY_RETURN_REASONS
      : RECONCILIATION_RETURN_REASONS


  const requiredComplete =
    verificationItems.every(
      (item) =>
        Boolean(
          reviewChecks[item.key],
        ),
    )

  const completedCount =
    verificationItems.filter(
      (item) =>
        Boolean(
          reviewChecks[item.key],
        ),
    ).length

  const buildApprovalComment = () => {
    if (isDataQualityCase) {
      const issueLabel =
        formatLabel(
          dataQualityIssue?.issueType,
        )

      const keyText =
        dataQualityIssue?.keyValue
          ? ` (${dataQualityIssue.keyValue})`
          : ''

      return `Independently reviewed the original uploaded banking dataset and verified the affected records for ${issueLabel}${keyText}. The Maker's root-cause assessment (${formatLabel(
        caseRecord?.rootCauseCategory,
      )}) and recommended remediation (${formatLabel(
        caseRecord?.proposedAction,
      )}) are supported by the evidence. The recommendation preserves the original BankSync upload and requires source correction followed by BankSync verification before reconciliation use.`
    }

    return `Independently reviewed the source and target reconciliation datasets, compared the relevant transaction identifiers and evidence, and confirmed that the Maker's root-cause assessment (${formatLabel(
      caseRecord?.rootCauseCategory,
    )}) and proposed action (${formatLabel(
      caseRecord?.proposedAction,
    )}) are supported by the reconciliation evidence.`
  }

  const buildReturnComment = (
    reason,
  ) => {
    const messages = {
      EVIDENCE_OVERLOOKED:
        'Independent review found relevant evidence that was not addressed in the Maker investigation. Re-review the underlying dataset evidence and update the findings before resubmission.',

      INSUFFICIENT_EVIDENCE:
        'The submitted investigation does not contain enough evidence to support the current conclusion. Add the missing supporting evidence and resubmit for Checker review.',

      ROOT_CAUSE_UNCLEAR:
        'The evidence reviewed does not clearly support the stated root cause. Reassess the root-cause explanation and show how it follows from the verified records.',

      DATASET_REVIEW_INCOMPLETE:
        isDataQualityCase
          ? 'The original uploaded dataset has not been reviewed completely enough to support approval. Re-check the affected records and any relevant rejected rows before resubmission.'
          : 'The source/target dataset review is incomplete. Re-check the relevant reconciliation records and any rejected rows before resubmission.',

      TRANSACTION_COMPARISON_INCORRECT:
        isDataQualityCase
          ? 'The affected-record verification is incomplete or inconsistent with the underlying data. Re-check the transaction identifiers and affected evidence before resubmission.'
          : 'The transaction comparison is incomplete or inconsistent with the underlying reconciliation data. Re-check the relevant identifiers and fields before resubmission.',

      ACTION_NOT_SUPPORTED:
        'The proposed action is not sufficiently supported by the verified evidence. Reassess the recommended action and explain why it is operationally appropriate.',

      RESOLUTION_INCOMPLETE:
        isDataQualityCase
          ? 'The remediation instruction is incomplete. Clarify what source-data correction is required and how the corrected upload will be verified before reconciliation use.'
          : 'The proposed resolution is incomplete. Clarify the corrective action and how completion will be verified.',

      OTHER:
        'Independent Checker review identified an issue that must be corrected before approval. See the Checker findings and update the investigation accordingly.',
    }

    return (
      messages[reason] ||
      ''
    )
  }

  const generateCheckerComment = () => {
    const generated =
      returnReason
        ? buildReturnComment(
            returnReason,
          )
        : buildApprovalComment()

    setCheckerComment(generated)
    setCommentAutoGenerated(true)
    setError('')
    setSuccess('')
  }

  useEffect(() => {
    if (!canReview) {
      return
    }

    /*
     * Auto-draft Checker comment:
     *
     * - choosing a Return Reason creates a
     *   return-oriented draft immediately.
     * - completing all required checks creates
     *   an approval-oriented draft.
     *
     * The draft remains fully editable.
     */
    if (returnReason) {
      setCheckerComment(
        buildReturnComment(
          returnReason,
        ),
      )
      setCommentAutoGenerated(true)
      return
    }

    if (requiredComplete) {
      setCheckerComment(
        buildApprovalComment(),
      )
      setCommentAutoGenerated(true)
    }
  }, [
    returnReason,
    requiredComplete,
  ])

  if (!canReview) {
    return null
  }

  const toggleReview = (key) => {
    setReviewChecks(
      (current) => ({
        ...current,
        [key]: !current[key],
      }),
    )

    setError('')
    setSuccess('')
  }

  const handleApprove = async () => {
    setError('')
    setSuccess('')

    if (!requiredComplete) {
      setError(
        'Complete all required independent verification before approving the case.',
      )
      return
    }

    setProcessingAction('approve')

    try {
      const response =
        await apiRequest(
          `/cases/${caseRecord._id}/approve`,
          {
            method: 'POST',
            body: JSON.stringify({
              checkerReview:
                reviewChecks,

              checkerComment:
                checkerComment.trim(),
            }),
          },
        )

      setSuccess(
        response.message ||
          (isDataQualityCase
            ? 'Data Quality investigation approved successfully.'
            : 'Case approved successfully.'),
      )

      if (onCaseUpdated) {
        await onCaseUpdated()
      }
    } catch (err) {
      const missing =
        err?.data
          ?.missingRequirements

      if (
        Array.isArray(missing) &&
        missing.length > 0
      ) {
        setError(
          `Verification incomplete: ${missing.join(
            ', ',
          )}`,
        )
      } else {
        setError(
          err.message ||
            'Unable to approve case.',
        )
      }
    } finally {
      setProcessingAction(null)
    }
  }

  const handleReturn = async () => {
    setError('')
    setSuccess('')

    if (!returnReason) {
      setError(
        'Select a return reason.',
      )
      return
    }

    if (
      checkerComment.trim().length <
      3
    ) {
      setError(
        'Explain the evidence or problem the Maker must correct.',
      )
      return
    }

    setProcessingAction('return')

    try {
      const response =
        await apiRequest(
          `/cases/${caseRecord._id}/return`,
          {
            method: 'POST',
            body: JSON.stringify({
              checkerReview:
                reviewChecks,

              checkerReturnReason:
                returnReason,

              checkerComment:
                checkerComment.trim(),
            }),
          },
        )

      setSuccess(
        response.message ||
          'Case returned to Maker.',
      )

      if (onCaseUpdated) {
        await onCaseUpdated()
      }
    } catch (err) {
      setError(
        err.message ||
          'Unable to return case.',
      )
    } finally {
      setProcessingAction(null)
    }
  }

  return (
    <section className="mt-6 rounded-2xl border border-stone-200 bg-white p-6 shadow-sm sm:p-8">
      <div className="flex items-start gap-3">
        <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-violet-50 text-violet-600">
          <ShieldCheck size={20} />
        </div>

        <div>
          <h2 className="font-semibold text-stone-900">
            Independent Checker Verification
          </h2>

          <p className="mt-1 text-sm leading-6 text-stone-500">
            {isDataQualityCase
              ? 'Independently verify the original banking dataset, affected records, Maker conclusion, and recommended remediation before accepting the pre-reconciliation data-integrity investigation.'
              : 'Independently verify the underlying reconciliation evidence before accepting the Maker’s conclusion.'}
          </p>
        </div>
      </div>

      {/* MAKER CONCLUSION SUMMARY */}
      <div className="mt-6 grid gap-4 sm:grid-cols-2">
        <div className="rounded-xl border border-stone-200 bg-stone-50 p-4">
          <p className="text-xs font-medium uppercase tracking-wide text-stone-400">
            Maker Root Cause
          </p>

          <p className="mt-2 text-sm font-semibold text-stone-900">
            {formatLabel(
              caseRecord
                ?.rootCauseCategory,
            )}
          </p>
        </div>

        <div className="rounded-xl border border-stone-200 bg-stone-50 p-4">
          <p className="text-xs font-medium uppercase tracking-wide text-stone-400">
            {isDataQualityCase
              ? 'Maker Recommended Remediation'
              : 'Maker Proposed Action'}
          </p>

          <p className="mt-2 text-sm font-semibold text-stone-900">
            {formatLabel(
              caseRecord
                ?.proposedAction,
            )}
          </p>
        </div>
      </div>

      {/* DATA QUALITY DETECTION SUMMARY */}
      {isDataQualityCase && (
        <div className="mt-4 grid gap-4 sm:grid-cols-3">
          <div className="rounded-xl border border-amber-200 bg-amber-50/50 p-4">
            <p className="text-xs font-medium uppercase tracking-wide text-stone-400">
              Detected Issue
            </p>

            <p className="mt-2 text-sm font-semibold text-stone-900">
              {formatLabel(
                dataQualityIssue?.issueType,
              )}
            </p>
          </div>

          <div className="rounded-xl border border-amber-200 bg-amber-50/50 p-4">
            <p className="text-xs font-medium uppercase tracking-wide text-stone-400">
              Detected Key
            </p>

            <p className="mt-2 font-mono text-sm font-semibold text-stone-900">
              {dataQualityIssue?.keyValue ||
                '—'}
            </p>
          </div>

          <div className="rounded-xl border border-amber-200 bg-amber-50/50 p-4">
            <p className="text-xs font-medium uppercase tracking-wide text-stone-400">
              Severity
            </p>

            <p className="mt-2 text-sm font-semibold text-stone-900">
              {formatLabel(
                dataQualityIssue?.severity,
              )}
            </p>
          </div>
        </div>
      )}

      {/* INDEPENDENT EVIDENCE MESSAGE */}
      <div className="mt-6 rounded-xl border border-violet-200 bg-violet-50/30 p-4">
        <p className="text-sm font-semibold text-stone-900">
          Independent evidence review
        </p>

        <p className="mt-1 text-sm leading-6 text-stone-500">
          {isDataQualityCase
            ? 'Do not approve from the Maker’s written explanation alone. Open the original uploaded dataset, independently inspect the affected records, and confirm whether the detected defect and proposed remediation are supported.'
            : 'Do not approve only from the Maker’s written explanation. Open the underlying source and target datasets and verify the important reconciliation evidence yourself.'}
        </p>
      </div>

      {/* CHECKLIST */}
      <div className="mt-8">
        <div className="flex flex-col gap-1 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <h3 className="font-semibold text-stone-900">
              Independent Verification Checklist
            </h3>

            <p className="mt-1 text-sm text-stone-500">
              Confirm each item only after
              performing the verification.
            </p>
          </div>

          <div className="mt-2 rounded-lg bg-stone-100 px-3 py-1.5 text-sm font-semibold text-stone-700 sm:mt-0">
            {completedCount}/
            {verificationItems.length}
          </div>
        </div>

        <div className="mt-4 space-y-3">
          {verificationItems.map(
            (item) => {
              const checked =
                Boolean(
                  reviewChecks[
                    item.key
                  ],
                )

              return (
                <button
                  key={item.key}
                  type="button"
                  onClick={() =>
                    toggleReview(
                      item.key,
                    )
                  }
                  className={`flex w-full items-start gap-3 rounded-xl border p-4 text-left transition ${
                    checked
                      ? 'border-emerald-200 bg-emerald-50'
                      : 'border-stone-200 bg-white hover:border-violet-200 hover:bg-violet-50/20'
                  }`}
                >
                  {checked ? (
                    <CheckCircle2
                      size={19}
                      className="mt-0.5 shrink-0 text-emerald-600"
                    />
                  ) : (
                    <Circle
                      size={19}
                      className="mt-0.5 shrink-0 text-stone-300"
                    />
                  )}

                  <div>
                    <p className="text-sm font-semibold text-stone-900">
                      {item.label}
                    </p>

                    <p className="mt-1 text-xs leading-5 text-stone-500">
                      {
                        item.description
                      }
                    </p>
                  </div>
                </button>
              )
            },
          )}
        </div>
      </div>

      {/* RETURN REASON */}
      <div className="mt-7 border-t border-stone-100 pt-6">
        <label
          htmlFor="returnReason"
          className="mb-2 block text-sm font-medium text-stone-700"
        >
          Return Reason
        </label>

        <select
          id="returnReason"
          value={returnReason}
          onChange={(event) => {
            setReturnReason(
              event.target.value,
            )
            setError('')
            setSuccess('')
          }}
          className="h-11 w-full rounded-xl border border-stone-200 bg-white px-3 text-sm text-stone-800 outline-none focus:border-violet-300"
        >
          {returnReasons.map(
            (item) => (
              <option
                key={item.value}
                value={item.value}
              >
                {item.label}
              </option>
            ),
          )}
        </select>

        <p className="mt-1 text-xs text-stone-400">
          Select a reason only when returning the investigation to the Maker. Choosing a reason automatically drafts the Checker comment below.
        </p>
      </div>

      {/* CHECKER COMMENT */}
      <div className="mt-5">
        <div className="mb-2 flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
          <label
            htmlFor="checkerComment"
            className="block text-sm font-medium text-stone-700"
          >
            Checker Findings / Comment
          </label>

          <button
            type="button"
            onClick={generateCheckerComment}
            className="w-fit rounded-lg border border-violet-200 bg-violet-50 px-3 py-1.5 text-xs font-semibold text-violet-700 transition hover:bg-violet-100"
          >
            Generate Comment
          </button>
        </div>

        <textarea
          id="checkerComment"
          rows={5}
          maxLength={1000}
          value={checkerComment}
          onChange={(event) => {
            setCheckerComment(
              event.target.value,
            )

            setCommentAutoGenerated(false)
            setError('')
          }}
          placeholder={
            isDataQualityCase
              ? 'Record what you independently verified in the original dataset and affected records. If returning the case, identify the evidence, root-cause, or remediation problem the Maker must address.'
              : 'Record what you verified. If returning the case, identify the specific conflicting or missing evidence the Maker must address.'
          }
          className="w-full resize-y rounded-xl border border-stone-200 p-3 text-sm text-stone-800 outline-none focus:border-violet-300"
        />

        <div className="mt-1 flex items-center justify-between gap-3">
          <p className="text-xs text-stone-400">
            {commentAutoGenerated
              ? 'Auto-generated draft — you can edit it before submitting.'
              : 'Editable Checker comment.'}
          </p>

          <div className="text-right text-xs text-stone-400">
            {checkerComment.length}/1000
          </div>
        </div>
      </div>

      {error && (
        <div className="mt-4 flex items-start gap-2 rounded-xl border border-red-200 bg-red-50 px-4 py-3">
          <AlertCircle
            size={17}
            className="mt-0.5 shrink-0 text-red-600"
          />

          <p className="text-sm text-red-700">
            {error}
          </p>
        </div>
      )}

      {success && (
        <div className="mt-4 flex items-start gap-2 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3">
          <CheckCircle2
            size={17}
            className="mt-0.5 shrink-0 text-emerald-600"
          />

          <p className="text-sm text-emerald-700">
            {success}
          </p>
        </div>
      )}

      {/* ACTIONS */}
      <div className="mt-6 flex flex-col gap-3 border-t border-stone-100 pt-5 sm:flex-row">
        <button
          type="button"
          onClick={handleApprove}
          disabled={
            Boolean(
              processingAction,
            ) ||
            !requiredComplete
          }
          className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-emerald-600 px-5 text-sm font-semibold text-white transition hover:bg-emerald-700 disabled:cursor-not-allowed disabled:opacity-40"
        >
          <CheckCircle2 size={17} />

          {processingAction ===
          'approve'
            ? 'Approving...'
            : isDataQualityCase
              ? 'Approve Investigation'
              : 'Approve Verified Case'}
        </button>

        <button
          type="button"
          onClick={handleReturn}
          disabled={Boolean(
            processingAction,
          )}
          className="inline-flex h-11 items-center justify-center gap-2 rounded-xl border border-red-200 bg-red-50 px-5 text-sm font-semibold text-red-700 transition hover:bg-red-100 disabled:cursor-not-allowed disabled:opacity-50"
        >
          <RotateCcw size={17} />

          {processingAction ===
          'return'
            ? 'Returning...'
            : 'Return with Findings'}
        </button>
      </div>

      {isDataQualityCase && (
        <div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3">
          <p className="text-xs leading-5 text-amber-800">
            Approving this investigation
            confirms the Maker’s analysis
            and remediation recommendation.
            It does not mean the underlying
            Data Quality defect has been
            corrected or verified resolved.
          </p>
        </div>
      )}
    </section>
  )
}

export default CheckerReviewPanel
